# Generated by Django 5.0.10 on 2025-11-09 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=10, help_text='Maximum number of requests per day.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the limit is active.')),
            ],
            options={
                'verbose_name': 'Limit',
                'verbose_name_plural': 'Limits',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='EssayEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='', help_text='A user-friendly error message.')),
                ('error_details', models.TextField(blank=True, default='', help_text='The detailed error information.')),
                ('essay_prompt', models.TextField(blank=True, default='', help_text='The prompt for the essay.', max_length=1000)),
                ('essay_text', models.TextField(help_text='The essay text.', max_length=5000)),
                ('essay_text_corrected', models.TextField(blank=True, default='', help_text='The corrected essay text.', max_length=5000)),
                ('surface_correction', models.JSONField(blank=True, default=dict, help_text='The surface level correction of the essay.')),
                ('deep_correction', models.JSONField(blank=True, default=dict, help_text='The deep level correction of the essay.')),
                ('score', models.FloatField(blank=True, help_text='The score of the essay.', null=True)),
                ('completed_tasks', models.IntegerField(default=0, help_text='Number of completed processing tasks.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
