# Generated by Django 5.0.10 on 2025-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, default='', help_text='Error message that displays to the user.')),
                ('error_details', models.TextField(blank=True, default='', help_text='Error details to diagnose the error.')),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('essay_prompt', models.TextField(blank=True, default='', help_text='The prompt for the essay.', max_length=1000)),
                ('essay_text', models.TextField(help_text='The essay text.', max_length=5000)),
                ('surface_correction', models.JSONField(default=dict, help_text='The surface level correction of the essay.')),
                ('deep_correction', models.JSONField(default=dict, help_text='The deep level correction of the essay.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
