# Generated by Django 5.0.10 on 2025-04-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayevaluation',
            name='essay_text_corrected',
            field=models.TextField(blank=True, default='', help_text='The corrected essay text.', max_length=5000),
        ),
    ]
