# Generated by Django 5.0.10 on 2025-04-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_essayevaluation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayevaluation',
            name='score',
            field=models.FloatField(blank=True, help_text='The score of the essay.', null=True),
        ),
        migrations.AlterField(
            model_name='essayevaluation',
            name='deep_correction',
            field=models.JSONField(blank=True, default=dict, help_text='The deep level correction of the essay.'),
        ),
        migrations.AlterField(
            model_name='essayevaluation',
            name='surface_correction',
            field=models.JSONField(blank=True, default=dict, help_text='The surface level correction of the essay.'),
        ),
    ]
