# Generated by Django 5.0.10 on 2025-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_essayevaluation_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayevaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='essayevaluation',
            name='completed_tasks',
            field=models.IntegerField(default=0, help_text='Number of completed processing tasks.'),
        ),
    ]
