# Generated by Django 5.0.10 on 2025-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_essayevaluation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=10, help_text='Maximum number of requests per day.')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
