# Generated by Django 5.0.10 on 2025-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_evaluationquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationquota',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the quota is active.'),
        ),
    ]
