# Generated by Django 5.0.10 on 2025-06-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_evaluationquota_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayevaluation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usage', 'verbose_name_plural': 'Usages'},
        ),
        migrations.AlterModelOptions(
            name='evaluationquota',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Quota', 'verbose_name_plural': 'Quotas'},
        ),
    ]
