# Generated by Django 5.0.10 on 2025-11-09 07:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=10, help_text='Order of the model in the UI (smaller number comes first)')),
                ('name', models.CharField(help_text="The model name for calling the LLM API (e.g., openai/gpt-4o-mini). Check <a href='https://docs.litellm.ai/docs/providers' target='_blank'>Litellm model list</a>.", max_length=200)),
                ('display_name', models.CharField(help_text='Display name for the model (e.g., GPT-4o)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only active models will be listed in the UI')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['order'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fake_llm_request', models.BooleanField(default=False, help_text='If True, LLM requests will return fake responses instead of making real API calls')),
                ('task_delay_seconds', models.IntegerField(default=0, help_text='The delay in seconds for LLM requests')),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
            },
        ),
        migrations.CreateModel(
            name='LimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_limit', models.IntegerField(default=10, help_text='Maximum number of requests per day for this model')),
                ('model', models.OneToOneField(help_text='The LLM model this limit applies to', on_delete=django.db.models.deletion.CASCADE, related_name='limit_config', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'Model Limit',
                'verbose_name_plural': 'Model Limits',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', help_text='Name of the environment variable (e.g, OPENAI_API_KEY)', max_length=255)),
                ('key', models.CharField(help_text="The API key (e.g., OpenAI starts with 'sk-')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only active keys will be used')),
                ('model', models.ForeignKey(blank=True, help_text='The LLM model this key is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='', help_text='A user-friendly error message.')),
                ('error_details', models.TextField(blank=True, default='', help_text='The detailed error information.')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Meta data for the request')),
                ('input_json', models.JSONField(blank=True, default=dict, help_text='Input JSON to be filled in the prompt')),
                ('result', models.TextField(blank=True, default='', help_text='The raw response from the LLM')),
                ('user_prompt_template', models.TextField(blank=True, default='', help_text='The user prompt template')),
                ('user_prompt', models.TextField(blank=True, default='', help_text='The actual prompt sent to the LLM')),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - True means this request is deleted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='The LLM model used for this request', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'LLM Request Record',
                'verbose_name_plural': 'LLM Request Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('surface_correction', 'Surface Correction'), ('surface_explain', 'Surface Explain'), ('macro_correction', 'Macro Correction'), ('micro_correction', 'Micro Correction'), ('score', 'Score')], help_text='The purpose of this configuration', max_length=50)),
                ('user_prompt_template', models.TextField(help_text='The user prompt template for the LLM.')),
                ('temperature', models.FloatField(default=0.7, help_text='Value between 0 and 2', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('example_output', models.TextField(blank=True, default='', help_text='Example output. Will be used as the fake response for debugging.')),
                ('delay_seconds_in_fake_mode', models.IntegerField(default=0, help_text='The delay in seconds for LLM requests in fake mode')),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active per purpose')),
                ('model', models.ForeignKey(help_text='The LLM model this config applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'Model Config',
                'verbose_name_plural': 'Model Configs',
                'get_latest_by': 'created_at',
            },
        ),
    ]
