# Generated by Django 5.0.10 on 2025-11-10 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=10, help_text='Controls the display order in the interface (lower numbers appear earlier).')),
                ('name', models.CharField(help_text="API identifier used when calling the LLM (e.g., openai/gpt-4o-mini). Refer to the <a href='https://docs.litellm.ai/docs/providers' target='_blank'>Litellm model catalog</a> for valid names.", max_length=200)),
                ('display_name', models.CharField(help_text='Readable name shown in the interface (e.g., GPT-4o).', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, this model will not be available in the interface.')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['order'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fake_llm_request', models.BooleanField(default=False, help_text='When enabled, fake responses are returned instead of real API calls (useful for testing).')),
                ('task_delay_seconds', models.IntegerField(default=0, help_text='Adds a delay (in seconds) before executing LLM tasks, useful for throttling or testing.')),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
            },
        ),
        migrations.CreateModel(
            name='LimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_limit', models.IntegerField(default=10, help_text='Maximum number of requests allowed per user per day for this model.')),
                ('model', models.OneToOneField(help_text='Specifies which LLM model this limit applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='limit_config', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'Model Limit',
                'verbose_name_plural': 'Model Limits',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', help_text='Environment variable name (e.g., OPENAI_API_KEY).', max_length=255)),
                ('key', models.CharField(help_text="Actual API key string (e.g., OpenAI keys usually start with 'sk-').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive keys will be ignored when making requests.')),
                ('model', models.ForeignKey(blank=True, help_text='Model linked to this API key (leave blank if it’s a global key).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='', help_text='A user-friendly error message.')),
                ('error_details', models.TextField(blank=True, default='', help_text='The detailed error information.')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Optional metadata providing extra context for this request.')),
                ('input_json', models.JSONField(blank=True, default=dict, help_text='JSON input data used to populate placeholders in the prompt.')),
                ('result', models.TextField(blank=True, default='', help_text='Raw response text returned from the LLM API.')),
                ('user_prompt_template', models.TextField(blank=True, default='', help_text='The original prompt template prior to variable substitution.')),
                ('user_prompt', models.TextField(blank=True, default='', help_text='The actual prompt string sent to the LLM API.')),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks this record as deleted without removing it from the database.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='Which LLM model was used to handle this request.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'LLM Request Record',
                'verbose_name_plural': 'LLM Request Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('surface_correction', 'Surface Correction'), ('surface_explain', 'Surface Explain'), ('macro_correction', 'Macro Correction'), ('micro_correction', 'Micro Correction'), ('score', 'Score')], help_text='Select the intended function or use case for this configuration.', max_length=50)),
                ('user_prompt_template', models.TextField(help_text='Prompt pattern including placeholders for variable data.')),
                ('temperature', models.FloatField(default=0.7, help_text='Randomness control: a value between 0.0 and 2.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('example_output', models.TextField(blank=True, default='', help_text='Sample output used when running in fake mode for debugging.')),
                ('delay_seconds_in_fake_mode', models.IntegerField(default=0, help_text='Artificial delay (in seconds) to simulate processing time in fake mode.')),
                ('is_active', models.BooleanField(default=False, help_text='If enabled, this will be the active configuration for the selected purpose.')),
                ('model', models.ForeignKey(help_text='The model linked to this configuration (can be left blank if removed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to='llm_gateway.llmmodel')),
            ],
            options={
                'verbose_name': 'Model Config',
                'verbose_name_plural': 'Model Configs',
                'get_latest_by': 'created_at',
            },
        ),
    ]
