# Generated by Django 5.0.10 on 2025-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='example_output',
            field=models.TextField(blank=True, default='', help_text='Example output. Will be used as the fake response for debugging.'),
        ),
    ]
