# Generated by Django 5.0.10 on 2025-04-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0002_llmconfig_example_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('surface_correction', 'Surface Correction'), ('surface_explain', 'Surface Explain'), ('macro_correction', 'Macro Correction'), ('micro_correction', 'Micro Correction'), ('score', 'Score')], help_text='The purpose of this configuration', max_length=50),
        ),
    ]
