# Generated by Django 5.0.10 on 2025-04-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0003_alter_llmconfig_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='delay_seconds_in_fake_mode',
            field=models.IntegerField(default=0, help_text='The delay in seconds for LLM requests in fake mode'),
        ),
    ]
