# Generated by Django 5.0.10 on 2025-06-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0004_llmconfig_delay_seconds_in_fake_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='llmconfig',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Model Config', 'verbose_name_plural': 'Model Configs'},
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'get_latest_by': 'created_at', 'ordering': ['order'], 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='llmsettings',
            options={'verbose_name': 'OpenAI Settings', 'verbose_name_plural': 'OpenAI Settings'},
        ),
        migrations.AlterModelOptions(
            name='quotaconfig',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Model Quota', 'verbose_name_plural': 'Model Quotas'},
        ),
    ]
