# Generated by Django 5.0.10 on 2025-02-08 03:12

import backend.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_course_options_course_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.users.models.CustomUserManager()),
            ],
        ),
    ]
