# Generated by Django 5.0.10 on 2025-06-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_course_created_at_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='managed_courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
